version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        GITHUB_REPOSITORY: shayanabbas/todo
    volumes:
      - ..:/workspaces/todo
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-net

volumes:
  postgres-data:

networks:
  todo-net:
    driver: bridge
